# coding: utf-8

"""
    Kalshi Trade API

    This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@kalshi.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import kalshi_python
from kalshi_python.models.get_positions_response import GetPositionsResponse  # noqa: E501
from kalshi_python.rest import ApiException


class TestGetPositionsResponse(unittest.TestCase):
    """GetPositionsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetPositionsResponse(self):
        """Test GetPositionsResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = kalshi_python.models.get_positions_response.GetPositionsResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
