# coding: utf-8

"""
    Kalshi Trade API

    This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@kalshi.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class BatchCreateOrdersIndividualResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'error': 'JSONError',
        'order': 'OrderConfirmation'
    }

    attribute_map = {
        'error': 'error',
        'order': 'order'
    }

    def __init__(self, error=None, order=None):  # noqa: E501
        """BatchCreateOrdersIndividualResponse - a model defined in Swagger"""  # noqa: E501
        self._error = None
        self._order = None
        self.discriminator = None
        if error is not None:
            self.error = error
        if order is not None:
            self.order = order

    @property
    def error(self):
        """Gets the error of this BatchCreateOrdersIndividualResponse.  # noqa: E501


        :return: The error of this BatchCreateOrdersIndividualResponse.  # noqa: E501
        :rtype: JSONError
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this BatchCreateOrdersIndividualResponse.


        :param error: The error of this BatchCreateOrdersIndividualResponse.  # noqa: E501
        :type: JSONError
        """

        self._error = error

    @property
    def order(self):
        """Gets the order of this BatchCreateOrdersIndividualResponse.  # noqa: E501


        :return: The order of this BatchCreateOrdersIndividualResponse.  # noqa: E501
        :rtype: OrderConfirmation
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this BatchCreateOrdersIndividualResponse.


        :param order: The order of this BatchCreateOrdersIndividualResponse.  # noqa: E501
        :type: OrderConfirmation
        """

        self._order = order

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BatchCreateOrdersIndividualResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BatchCreateOrdersIndividualResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
