# coding: utf-8

"""
    Kalshi Trade API

    This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@kalshi.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DecreaseOrderRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'reduce_by': 'int',
        'reduce_to': 'int'
    }

    attribute_map = {
        'reduce_by': 'reduce_by',
        'reduce_to': 'reduce_to'
    }

    def __init__(self, reduce_by=None, reduce_to=None):  # noqa: E501
        """DecreaseOrderRequest - a model defined in Swagger"""  # noqa: E501
        self._reduce_by = None
        self._reduce_to = None
        self.discriminator = None
        if reduce_by is not None:
            self.reduce_by = reduce_by
        if reduce_to is not None:
            self.reduce_to = reduce_to

    @property
    def reduce_by(self):
        """Gets the reduce_by of this DecreaseOrderRequest.  # noqa: E501

        Number of contracts to decrease the order's count by. One of reduce_by or reduce_to must be provided.  # noqa: E501

        :return: The reduce_by of this DecreaseOrderRequest.  # noqa: E501
        :rtype: int
        """
        return self._reduce_by

    @reduce_by.setter
    def reduce_by(self, reduce_by):
        """Sets the reduce_by of this DecreaseOrderRequest.

        Number of contracts to decrease the order's count by. One of reduce_by or reduce_to must be provided.  # noqa: E501

        :param reduce_by: The reduce_by of this DecreaseOrderRequest.  # noqa: E501
        :type: int
        """

        self._reduce_by = reduce_by

    @property
    def reduce_to(self):
        """Gets the reduce_to of this DecreaseOrderRequest.  # noqa: E501

        Number of contracts to decrease the order to.  If the orders remaining count is lower, it does nothing. One of reduce_by or reduce_to must be provided  # noqa: E501

        :return: The reduce_to of this DecreaseOrderRequest.  # noqa: E501
        :rtype: int
        """
        return self._reduce_to

    @reduce_to.setter
    def reduce_to(self, reduce_to):
        """Sets the reduce_to of this DecreaseOrderRequest.

        Number of contracts to decrease the order to.  If the orders remaining count is lower, it does nothing. One of reduce_by or reduce_to must be provided  # noqa: E501

        :param reduce_to: The reduce_to of this DecreaseOrderRequest.  # noqa: E501
        :type: int
        """

        self._reduce_to = reduce_to

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DecreaseOrderRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DecreaseOrderRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
