# coding: utf-8

"""
    Kalshi Trade API

    This documentation describes Kalshi's trading API (known as Trade API v2). By using this API, you agree to Kalshi's Developer Agreement (https://kalshi.com/developer-agreement).  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: support@kalshi.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetEventResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'event': 'EventData',
        'markets': 'list[Market]'
    }

    attribute_map = {
        'event': 'event',
        'markets': 'markets'
    }

    def __init__(self, event=None, markets=None):  # noqa: E501
        """GetEventResponse - a model defined in Swagger"""  # noqa: E501
        self._event = None
        self._markets = None
        self.discriminator = None
        self.event = event
        self.markets = markets

    @property
    def event(self):
        """Gets the event of this GetEventResponse.  # noqa: E501


        :return: The event of this GetEventResponse.  # noqa: E501
        :rtype: EventData
        """
        return self._event

    @event.setter
    def event(self, event):
        """Sets the event of this GetEventResponse.


        :param event: The event of this GetEventResponse.  # noqa: E501
        :type: EventData
        """
        if event is None:
            raise ValueError("Invalid value for `event`, must not be `None`")  # noqa: E501

        self._event = event

    @property
    def markets(self):
        """Gets the markets of this GetEventResponse.  # noqa: E501

        Data for the markets in this event.  # noqa: E501

        :return: The markets of this GetEventResponse.  # noqa: E501
        :rtype: list[Market]
        """
        return self._markets

    @markets.setter
    def markets(self, markets):
        """Sets the markets of this GetEventResponse.

        Data for the markets in this event.  # noqa: E501

        :param markets: The markets of this GetEventResponse.  # noqa: E501
        :type: list[Market]
        """
        if markets is None:
            raise ValueError("Invalid value for `markets`, must not be `None`")  # noqa: E501

        self._markets = markets

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetEventResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetEventResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
